# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
    - master
pr:
- master

variables:
  - name: versionHadolint
    value: 'v1.16.3'

jobs:

- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'
